language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
after_script:
  - rm -rf tmp
notifications:
  hipchat:
    rooms:
      - secure: MCy/NKTTKlQmeTlu4zYoq2sXd06gdq9o1uwAwhqkfikL7VVkK2aCljBXAzAGt103U97ADIg7vPu2YVjCRVHRu6Ix6f0LIZKw5DPiNGxU1DUZsf5Yn4O7eahSnUittAjlzHyRjJBFn/LdQB5aQ93JwpESPvwv6ct1wUroMQZbTp0=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> / <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: always
branches:
  only:
    - master
